import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: ['src/index.ts'],
  format: 'esm',
  platform: 'node',
  target: 'node22',
  dts: false,
  clean: true,
  sourcemap: true,
  banner: {
    js: '#!/usr/bin/env node',
  },
  outputOptions: {
    codeSplitting: false,
    entryFileNames: '[name].js',
    chunkFileNames: '[name]-[hash].js',
  },
  deps: {
    alwaysBundle: [
      /^@seo-solver\/(?!fetch-playwright$)/,
      '@adobe/structured-data-validator',
      'ansi-regex',
      'ansis',
      'boolbase',
      'chalk',
      'cheerio',
      'cheerio-select',
      'cmd-ts',
      'css-select',
      'css-what',
      'debug',
      'didyoumean',
      'domelementtype',
      'domhandler',
      'dom-serializer',
      'domutils',
      'encoding-sniffer',
      'entities',
      'has-flag',
      'htmlparser2',
      'iconv-lite',
      'ms',
      'nth-check',
      'parse5',
      'parse5-htmlparser2-tree-adapter',
      'parse5-parser-stream',
      'safer-buffer',
      'strip-ansi',
      'supports-color',
      'undici',
      'whatwg-encoding',
      'whatwg-mimetype',
    ],
    onlyBundle: [
      /^@seo-solver\/(?!fetch-playwright$)/,
      '@adobe/structured-data-validator',
      'ansi-regex',
      'ansis',
      'boolbase',
      'chalk',
      'cheerio',
      'cheerio-select',
      'cmd-ts',
      'css-select',
      'css-what',
      'debug',
      'didyoumean',
      'domelementtype',
      'domhandler',
      'dom-serializer',
      'domutils',
      'encoding-sniffer',
      'entities',
      'has-flag',
      'htmlparser2',
      'iconv-lite',
      'ms',
      'nth-check',
      'parse5',
      'parse5-htmlparser2-tree-adapter',
      'parse5-parser-stream',
      'safer-buffer',
      'strip-ansi',
      'supports-color',
      'undici',
      'whatwg-encoding',
      'whatwg-mimetype',
    ],
    neverBundle: ['@seo-solver/fetch-playwright'],
  },
});
