import type { ComparisonReport, DiffEntry } from '@seo-solver/types/compare';
import type { ReporterConfig } from '@seo-solver/types/report';
import { summarizeComparison } from '../../summary';
import { escapeHtml, formatDiffLabel, formatDiffPath, formatStatus, formatTypeLabel } from '../../utils/text';
import { formatFullValue } from '../../utils/truncate';
import { renderHtml } from './template';

function renderComparisonRows(diffs: DiffEntry[]): string {
  const rows = diffs.map((diff) => {
    const label = escapeHtml(formatDiffLabel(diff.kind));
    const path = diff.path === '' ? '(entire type)' : formatDiffPath(diff);
    const badge = `<span class="kind-badge ${diff.kind}">${label}</span>`;

    if (diff.kind === 'changed') {
      const beforeVal = escapeHtml(formatFullValue(diff.before));
      const afterVal = escapeHtml(formatFullValue(diff.after));
      return `<tr class="diff-start">
  <td rowspan="2">${badge}</td>
  <td rowspan="2"><code>${escapeHtml(path)}</code></td>
  <td class="cell-before"><code>${beforeVal}</code></td>
</tr>
<tr class="diff-after">
  <td class="cell-after"><code>${afterVal}</code></td>
</tr>`;
    }

    if (diff.kind === 'added') {
      const afterVal = escapeHtml(formatFullValue(diff.after));
      return `<tr class="diff-start">
  <td>${badge}</td>
  <td><code>${escapeHtml(path)}</code></td>
  <td class="cell-after"><code>${afterVal}</code></td>
</tr>`;
    }

    // removed
    const beforeVal = escapeHtml(formatFullValue(diff.before));
    return `<tr class="diff-start">
  <td>${badge}</td>
  <td><code>${escapeHtml(path)}</code></td>
  <td class="cell-before"><code>${beforeVal}</code></td>
</tr>`;
  });

  return `<table>
  <thead>
    <tr><th>Change</th><th>Path</th><th>Value</th></tr>
  </thead>
  <tbody>
${rows.join('\n')}
  </tbody>
</table>`;
}

export function formatHtmlComparison(report: ComparisonReport, _config: ReporterConfig): string {
  const summary = summarizeComparison(report);
  const sections = report.comparisons.map((comparison) => {
    if (comparison.diffs.length === 0) {
      return {
        body: '<details><summary>Identical</summary><p class="muted">No differences found.</p></details>',
        status: 'Identical',
        title: formatTypeLabel(comparison.type),
      };
    }

    return {
      body: renderComparisonRows(comparison.diffs),
      status: `${comparison.diffs.length} diff${comparison.diffs.length === 1 ? '' : 's'}`,
      title: formatTypeLabel(comparison.type),
    };
  });

  return renderHtml({
    footer: 'Generated by seo-solver',
    header: `<div class="badges">
  <span><strong>A:</strong> ${escapeHtml(report.urlA)} · ${escapeHtml(formatStatus(report.fetchA.statusCode))} (${report.fetchA.timing}ms)</span>
  <span><strong>B:</strong> ${escapeHtml(report.urlB)} · ${escapeHtml(formatStatus(report.fetchB.statusCode))} (${report.fetchB.timing}ms)</span>
</div>`,
    sections,
    summary: [
      `<span class="badge changed">${summary.changed} changed</span>`,
      `<span class="badge added">${summary.added} added</span>`,
      `<span class="badge removed">${summary.removed} removed</span>`,
      `<span class="badge">${summary.identical} identical</span>`,
    ].join(''),
    title: 'SEO Comparison',
  });
}
