import type { ComparisonReport, DiffEntry } from '@seo-solver/types/compare';
import type { ReporterConfig } from '@seo-solver/types/report';
import { summarizeComparison } from '../../summary.js';
import {
  escapeHtml,
  formatDiffLabel,
  formatDiffMarkdownAfter,
  formatDiffMarkdownBefore,
  formatDiffPath,
  formatStatus,
  formatTypeLabel,
} from '../../utils/text.js';
import { renderHtml } from './template.js';

function renderComparisonRows(diffs: DiffEntry[]): string {
  return `<table>
    <thead>
      <tr><th>Change</th><th>Path</th><th>Before</th><th>After</th></tr>
    </thead>
    <tbody>
      ${diffs
        .map(
          (diff) => `<tr>
        <td class="${diff.kind}">${escapeHtml(formatDiffLabel(diff.kind))}</td>
        <td><code>${escapeHtml(formatDiffPath(diff))}</code></td>
        <td>${escapeHtml(formatDiffMarkdownBefore(diff, false))}</td>
        <td>${escapeHtml(formatDiffMarkdownAfter(diff, false))}</td>
      </tr>`,
        )
        .join('')}
    </tbody>
  </table>`;
}

export function formatHtmlComparison(report: ComparisonReport, _config: ReporterConfig): string {
  const summary = summarizeComparison(report);
  const sections = report.comparisons.map((comparison) => {
    if (comparison.diffs.length === 0) {
      return {
        body: '<details><summary>Identical</summary><p class="muted">No differences found.</p></details>',
        status: 'Identical',
        title: formatTypeLabel(comparison.type),
      };
    }

    return {
      body: renderComparisonRows(comparison.diffs),
      status: `${comparison.diffs.length} diff${comparison.diffs.length === 1 ? '' : 's'}`,
      title: formatTypeLabel(comparison.type),
    };
  });

  return renderHtml({
    footer: 'Generated by seo-solver',
    header: `<div class="badges">
  <span><strong>A:</strong> ${escapeHtml(report.urlA)} · ${escapeHtml(formatStatus(report.fetchA.statusCode))} (${report.fetchA.timing}ms)</span>
  <span><strong>B:</strong> ${escapeHtml(report.urlB)} · ${escapeHtml(formatStatus(report.fetchB.statusCode))} (${report.fetchB.timing}ms)</span>
</div>`,
    sections,
    summary: [
      `<span class="badge changed">${summary.changed} changed</span>`,
      `<span class="badge added">${summary.added} added</span>`,
      `<span class="badge removed">${summary.removed} removed</span>`,
      `<span class="badge">${summary.identical} identical</span>`,
    ].join(''),
    title: 'SEO Comparison',
  });
}
