import type { Diagnostic, ReporterConfig, ValidationReport } from '@seo-solver/types';
import { filterDiagnosticsBySeverity } from '../../filter.js';
import { summarizeValidation } from '../../summary.js';
import {
  escapeHtml,
  formatSeverityLabel,
  formatStatus,
  formatTimestamp,
  formatTypeLabel,
  getReportTitle,
} from '../../utils/text.js';
import { renderHtml } from './template.js';

function renderValidationRows(diagnostics: Diagnostic[]): string {
  return `<table>
    <thead>
      <tr><th>Severity</th><th>Rule</th><th>Message</th></tr>
    </thead>
    <tbody>
      ${diagnostics
        .map(
          (diagnostic) => `<tr>
        <td class="${diagnostic.severity}">${escapeHtml(formatSeverityLabel(diagnostic.severity))}</td>
        <td><code>${escapeHtml(diagnostic.rule)}</code></td>
        <td>${escapeHtml(diagnostic.message)}${
          diagnostic.actual !== undefined
            ? `<div class="muted"><code>${escapeHtml(String(diagnostic.actual))}</code></div>`
            : ''
        }</td>
      </tr>`,
        )
        .join('')}
    </tbody>
  </table>`;
}

export function formatHtmlValidation(report: ValidationReport, config: ReporterConfig): string {
  const summary = summarizeValidation(report);
  const sections = report.validations.map((validation) => {
    const visibleDiagnostics = filterDiagnosticsBySeverity(validation.diagnostics, config.minSeverity ?? 'info');
    const hasHiddenDiagnostics = validation.diagnostics.length > 0 && visibleDiagnostics.length === 0;

    if (visibleDiagnostics.length === 0) {
      if (hasHiddenDiagnostics) {
        return {
          body: '<p class="muted">No visible diagnostics at current minSeverity.</p>',
          status: 'Hidden by filter',
          title: formatTypeLabel(validation.type),
        };
      }

      return {
        body: '<details><summary>All checks passed</summary><p class="muted">No visible diagnostics.</p></details>',
        status: 'Passed',
        title: formatTypeLabel(validation.type),
      };
    }

    return {
      body: renderValidationRows(visibleDiagnostics),
      status: `${visibleDiagnostics.length} issue${visibleDiagnostics.length === 1 ? '' : 's'}`,
      title: formatTypeLabel(validation.type),
    };
  });

  return renderHtml({
    footer: 'Generated by seo-solver',
    header: `<p><strong>URL:</strong> ${escapeHtml(report.url)}</p>
<p><strong>Status:</strong> ${escapeHtml(formatStatus(report.fetch.statusCode))} (${report.fetch.timing}ms)</p>
<p><strong>Date:</strong> ${escapeHtml(formatTimestamp(report.timestamp))}</p>`,
    sections,
    summary: [
      `<span class="badge error">${summary.errors} errors</span>`,
      `<span class="badge warning">${summary.warnings} warnings</span>`,
      `<span class="badge info">${summary.info} info</span>`,
    ].join(''),
    title: `SEO Audit — ${getReportTitle(report.url)}`,
  });
}
