import type { Severity } from '@seo-solver/types/validate';

export type StaticRuleCatalogEntry = {
  rule: string;
  severity: Severity;
  validator: string;
  description: string;
};

export const STATIC_RULE_CATALOGS = {
  canonical: [
    {
      rule: 'canonical/missing',
      severity: 'warning',
      validator: 'canonical',
      description: 'Canonical link is missing',
    },
    {
      rule: 'canonical/relative-url',
      severity: 'warning',
      validator: 'canonical',
      description: 'Canonical URL is relative. Should be absolute',
    },
    {
      rule: 'canonical/mismatch-og-url',
      severity: 'warning',
      validator: 'canonical',
      description: 'Canonical URL does not match og:url',
    },
    {
      rule: 'canonical/hreflang-missing-x-default',
      severity: 'info',
      validator: 'canonical',
      description: 'hreflang is defined but x-default is missing',
    },
    {
      rule: 'canonical/hreflang-missing-self',
      severity: 'warning',
      validator: 'canonical',
      description: 'Current page URL is not included in hreflang entries',
    },
    {
      rule: 'canonical/hreflang-relative-url',
      severity: 'warning',
      validator: 'canonical',
      description: 'hreflang URL should be absolute',
    },
  ],
  headings: [
    { rule: 'headings/missing-h1', severity: 'error', validator: 'headings', description: 'Page has no <h1> heading' },
    {
      rule: 'headings/multiple-h1',
      severity: 'warning',
      validator: 'headings',
      description: 'Page has multiple <h1> headings',
    },
    {
      rule: 'headings/skipped-level',
      severity: 'warning',
      validator: 'headings',
      description: 'Heading level skipped',
    },
    { rule: 'headings/empty-heading', severity: 'warning', validator: 'headings', description: 'Empty heading found' },
    {
      rule: 'headings/first-not-h1',
      severity: 'info',
      validator: 'headings',
      description: 'First heading is not <h1>',
    },
  ],
  jsonld: [
    {
      rule: 'jsonld/missing-context',
      severity: 'error',
      validator: 'jsonld',
      description: 'JSON-LD object is missing @context',
    },
    {
      rule: 'jsonld/missing-type',
      severity: 'error',
      validator: 'jsonld',
      description: 'JSON-LD object is missing @type',
    },
    {
      rule: 'jsonld/empty-block',
      severity: 'warning',
      validator: 'jsonld',
      description: 'JSON-LD block is an empty object',
    },
    {
      rule: 'jsonld/duplicate-type',
      severity: 'info',
      validator: 'jsonld',
      description: 'Multiple JSON-LD blocks have the same @type',
    },
    {
      rule: 'jsonld/url-mismatch-canonical',
      severity: 'info',
      validator: 'jsonld',
      description: 'JSON-LD url does not match the canonical URL',
    },
    {
      rule: 'jsonld/name-mismatch-og-title',
      severity: 'info',
      validator: 'jsonld',
      description: 'JSON-LD name does not match og:title',
    },
    {
      rule: 'jsonld/image-mismatch-og-image',
      severity: 'info',
      validator: 'jsonld',
      description: 'JSON-LD image does not match og:image',
    },
    {
      rule: 'jsonld/adobe/schema-unavailable',
      severity: 'warning',
      validator: 'jsonld',
      description: 'Schema.org schema is unavailable, so Adobe validation was skipped',
    },
    {
      rule: 'jsonld/adobe/validation-failed',
      severity: 'warning',
      validator: 'jsonld',
      description: 'Adobe structured data validation failed and was skipped',
    },
  ],
  meta: [
    { rule: 'meta/title-missing', severity: 'error', validator: 'meta', description: '<title> tag is missing' },
    { rule: 'meta/title-empty', severity: 'error', validator: 'meta', description: '<title> tag is empty' },
    { rule: 'meta/title-too-long', severity: 'warning', validator: 'meta', description: 'Title exceeds 60 characters' },
    { rule: 'meta/title-too-short', severity: 'info', validator: 'meta', description: 'Title is very short' },
    {
      rule: 'meta/description-missing',
      severity: 'warning',
      validator: 'meta',
      description: 'Meta description is missing',
    },
    {
      rule: 'meta/description-too-long',
      severity: 'warning',
      validator: 'meta',
      description: 'Meta description exceeds 160 characters',
    },
    {
      rule: 'meta/description-too-short',
      severity: 'info',
      validator: 'meta',
      description: 'Meta description is very short',
    },
    {
      rule: 'meta/viewport-missing',
      severity: 'warning',
      validator: 'meta',
      description: 'Viewport meta tag is missing (required for mobile)',
    },
    {
      rule: 'meta/charset-missing',
      severity: 'info',
      validator: 'meta',
      description: 'Charset declaration is missing',
    },
  ],
  opengraph: [
    {
      rule: 'opengraph/title-missing',
      severity: 'error',
      validator: 'opengraph',
      description: 'og:title is required for social sharing',
    },
    {
      rule: 'opengraph/title-too-long',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:title exceeds 90 characters',
    },
    {
      rule: 'opengraph/title-mismatch-meta',
      severity: 'info',
      validator: 'opengraph',
      description: 'og:title differs substantially from the document title',
    },
    {
      rule: 'opengraph/description-missing',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:description is recommended for social sharing',
    },
    {
      rule: 'opengraph/description-too-long',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:description exceeds 200 characters',
    },
    {
      rule: 'opengraph/description-fallback-missing',
      severity: 'warning',
      validator: 'opengraph',
      description: 'Neither og:description nor meta description is present',
    },
    {
      rule: 'opengraph/image-missing',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:image is recommended for social sharing',
    },
    {
      rule: 'opengraph/image-not-absolute',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:image should be an absolute URL',
    },
    {
      rule: 'opengraph/image-http',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:image uses HTTP; Telegram and WhatsApp may not load it',
    },
    {
      rule: 'opengraph/image-missing-dimensions',
      severity: 'info',
      validator: 'opengraph',
      description: 'og:image is missing width or height metadata',
    },
    {
      rule: 'opengraph/image-missing-alt',
      severity: 'info',
      validator: 'opengraph',
      description: 'og:image:alt is missing',
    },
    {
      rule: 'opengraph/image-avif',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:image:type is image/avif, which Facebook does not reliably support',
    },
    {
      rule: 'opengraph/image-whatsapp-minimum',
      severity: 'info',
      validator: 'opengraph',
      description: 'og:image dimensions are below WhatsApp minimum recommendations',
    },
    {
      rule: 'opengraph/url-missing',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:url is recommended',
    },
    {
      rule: 'opengraph/url-not-absolute',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:url should be an absolute URL',
    },
    {
      rule: 'opengraph/url-mismatch-canonical',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:url does not match the canonical URL',
    },
    {
      rule: 'opengraph/type-missing',
      severity: 'info',
      validator: 'opengraph',
      description: "og:type defaults to 'website' when missing",
    },
    {
      rule: 'opengraph/type-invalid',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:type is not a recognized Open Graph type',
    },
    {
      rule: 'opengraph/locale-invalid-format',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:locale should use the xx_XX format',
    },
    {
      rule: 'opengraph/locale-mismatch-lang',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:locale does not match the page language',
    },
    {
      rule: 'opengraph/locale-alternate-mismatch-hreflang',
      severity: 'info',
      validator: 'opengraph',
      description: 'og:locale alternate values do not cover all hreflang languages',
    },
    {
      rule: 'opengraph/article-missing-published-time',
      severity: 'info',
      validator: 'opengraph',
      description: 'article:published_time is recommended for article pages',
    },
    {
      rule: 'opengraph/article-invalid-time-format',
      severity: 'warning',
      validator: 'opengraph',
      description: 'Article timestamps should use ISO 8601 format',
    },
    {
      rule: 'opengraph/article-modified-before-published',
      severity: 'warning',
      validator: 'opengraph',
      description: 'article:modified_time is earlier than article:published_time',
    },
    {
      rule: 'opengraph/video-missing-url',
      severity: 'warning',
      validator: 'opengraph',
      description: 'og:video:url is required for video Open Graph objects',
    },
    {
      rule: 'opengraph/video-missing-dimensions',
      severity: 'info',
      validator: 'opengraph',
      description: 'og:video is missing width or height metadata',
    },
  ],
  'robots-txt': [
    { rule: 'robots/empty-file', severity: 'info', validator: 'robots-txt', description: 'robots.txt is empty' },
    {
      rule: 'robots/no-wildcard-group',
      severity: 'info',
      validator: 'robots-txt',
      description: 'No rules for User-agent: * (wildcard)',
    },
    {
      rule: 'robots/sitemap-missing',
      severity: 'warning',
      validator: 'robots-txt',
      description: 'No Sitemap directive in robots.txt',
    },
    {
      rule: 'robots/sitemap-not-absolute',
      severity: 'warning',
      validator: 'robots-txt',
      description: 'Sitemap URL should be absolute',
    },
    {
      rule: 'robots/disallow-all',
      severity: 'warning',
      validator: 'robots-txt',
      description: 'All crawling is disallowed',
    },
    {
      rule: 'robots/crawl-delay-too-high',
      severity: 'info',
      validator: 'robots-txt',
      description: 'Crawl-delay may slow indexing',
    },
    {
      rule: 'robots/blocks-social-bots',
      severity: 'warning',
      validator: 'robots-txt',
      description: 'robots.txt blocks social crawler user agents',
    },
  ],
  twitter: [
    { rule: 'twitter/card-missing', severity: 'warning', validator: 'meta', description: 'twitter:card is missing' },
    {
      rule: 'twitter/card-invalid',
      severity: 'error',
      validator: 'meta',
      description: 'twitter:card must be one of summary, summary_large_image, app, or player',
    },
    {
      rule: 'twitter/title-too-long',
      severity: 'warning',
      validator: 'meta',
      description: 'twitter:title exceeds 70 characters',
    },
    {
      rule: 'twitter/description-too-long',
      severity: 'warning',
      validator: 'meta',
      description: 'twitter:description exceeds 200 characters',
    },
    {
      rule: 'twitter/image-alt-too-long',
      severity: 'warning',
      validator: 'meta',
      description: 'twitter:image:alt exceeds 420 characters',
    },
    {
      rule: 'twitter/site-invalid-handle',
      severity: 'warning',
      validator: 'meta',
      description: 'twitter:site should start with @',
    },
    {
      rule: 'twitter/app-missing-id',
      severity: 'error',
      validator: 'meta',
      description: 'App cards must provide an iPhone or Google Play app id',
    },
    {
      rule: 'twitter/app-incomplete-ios',
      severity: 'warning',
      validator: 'meta',
      description: 'twitter:app:name:iphone should accompany twitter:app:id:iphone',
    },
    {
      rule: 'twitter/app-incomplete-android',
      severity: 'warning',
      validator: 'meta',
      description: 'twitter:app:name:googleplay should accompany twitter:app:id:googleplay',
    },
    {
      rule: 'twitter/player-missing',
      severity: 'error',
      validator: 'meta',
      description: 'Player cards must include twitter:player',
    },
    {
      rule: 'twitter/player-not-https',
      severity: 'error',
      validator: 'meta',
      description: 'twitter:player must use HTTPS',
    },
    {
      rule: 'twitter/player-missing-dimensions',
      severity: 'error',
      validator: 'meta',
      description: 'Player cards must include twitter:player:width and twitter:player:height',
    },
    {
      rule: 'twitter/title-fallback-og',
      severity: 'info',
      validator: 'meta',
      description: 'twitter:title is missing and will fall back to og:title',
    },
    {
      rule: 'twitter/description-fallback-og',
      severity: 'info',
      validator: 'meta',
      description: 'twitter:description is missing and will fall back to og:description',
    },
    {
      rule: 'twitter/image-fallback-og',
      severity: 'info',
      validator: 'meta',
      description: 'twitter:image is missing and will fall back to og:image',
    },
    {
      rule: 'twitter/title-no-fallback',
      severity: 'error',
      validator: 'meta',
      description: 'Neither twitter:title nor og:title is present',
    },
    {
      rule: 'twitter/image-no-fallback',
      severity: 'error',
      validator: 'meta',
      description: 'Neither twitter:image nor og:image is present',
    },
  ],
  pinterest: [
    {
      rule: 'pinterest/nopin-detected',
      severity: 'info',
      validator: 'meta',
      description: 'Pinterest pinning is disabled with the nopin directive',
    },
    {
      rule: 'pinterest/og-image-vertical-recommended',
      severity: 'info',
      validator: 'meta',
      description: 'Pinterest recommends a dedicated vertical image when og:image is used',
    },
  ],
  vk: [{ rule: 'vk/image-present', severity: 'info', validator: '*', description: 'vk:image is present' }],
  applinks: [
    {
      rule: 'applinks/ios-incomplete',
      severity: 'warning',
      validator: 'opengraph',
      description: 'App Links iOS metadata is incomplete',
    },
    {
      rule: 'applinks/android-incomplete',
      severity: 'warning',
      validator: 'opengraph',
      description: 'App Links Android metadata is incomplete',
    },
  ],
  cross: [
    {
      rule: 'cross/noindex-with-seo',
      severity: 'info',
      validator: '*',
      description: 'The page is noindex but still includes SEO/social metadata',
    },
    {
      rule: 'cross/og-type-content-mismatch',
      severity: 'info',
      validator: '*',
      description: 'og:type is website even though article metadata is present',
    },
  ],
} as const satisfies Record<string, readonly StaticRuleCatalogEntry[]>;
